#!/usr/bin/env python
import os
import sys

argc = len(sys.argv)

if argc == 1:
	print("You should pass 1+ arguments.")
	exit()


def ip():
  import socket
  return socket.gethostbyname_ex(socket.gethostname())[-1][-1]

os.chdir(os.path.expanduser("~/NS3-SOP-Simulation"))

os.system("git add -A")
os.system("git commit -m \"[%s] %s\"" % (ip(), sys.argv[1]))
os.system("git push origin master")

